version: '2.3'
services:
  reconstructor:
    build: rbtmrecon/
    runtime: nvidia
    volumes:
      - /diskmnt/fast/robotom:/fast
      - /diskmnt/a/makov/robotom/:/storage
    restart: unless-stopped
    external_links:
      - rbtmstorage_server_1
    # network_mode: bridge
    networks:
      - default
      - rbtmstorage_default
    container_name: web_reconstructor_1
  reconstructor-jupyter:
    build: rbtmrecon/
    command: bash -c ". /opt/conda/etc/profile.d/conda.sh && conda activate xrecon && cd /rbtm/recon/ && jupyter notebook"
    runtime: nvidia
    volumes:
      - /diskmnt/fast/robotom:/fast
      - /diskmnt/a/makov/robotom/:/storage
    restart: unless-stopped
    external_links:
      - rbtmstorage_server_1
    # network_mode: bridge
    networks:
      - default
      - rbtmstorage_default
    ports:
      - "5551:5551"
    container_name: web_reconstructor_jupyter_1
  web:
    build: rbtmwebrecon/
    volumes:
      - /diskmnt/a/makov/robotom/:/webrbtm/webrecon/static/tomo_data
    restart: unless-stopped
    external_links:
      - rbtmstorage_server_1
    # network_mode: bridge
    networks:
      - default
      - rbtmstorage_default
    ports:
      - "5550:5550"
    container_name: web_web_1
  database:
    image: mongo:4.0
    # ports:
    #   - "27017:27017"
    # network_mode: bridge
    container_name: web_database_1
    volumes:
      - ./data/db:/data/db
    restart: unless-stopped

networks:
  rbtmstorage_default:
    external: true